namespace Comix.Cos.Models.EventModels.CosMallProduct;

public class CosProductDto
{
    public string ProductName { get; set; }
    public string ShortDescription { get; set; }
    public string CategoryCode { get; set; }
    public string ProductCode { get; set; }
    public string FirstCategoryCode { get; set; }
    public int TypeId { get; set; }
    public string BrandCode { get; set; }
    public int RegionId { get; set; }
    public string Unit { get; set; }
    public string wapdescription { get; set; }
    public string Unitname { get; set; }
    public string Saleunitname { get; set; }
    public string ProductSaleAttribute { get; set; }
    public decimal ProductRetailPrice { get; set; }
    public decimal ProductSaleUnitPrice { get; set; }
    public string PackageSAU { get; set; }
    public int SaleCounts { get; set; }
    public int Stock { get; set; }
    public decimal MarketPrice { get; set; }
    public decimal LowestSalePrice { get; set; }
    public bool HasSKU { get; set; }
    public int DisplaySequence { get; set; }
    public string Attribute1 { get; set; }
    public string Attribute2 { get; set; }
    public string Attribute3 { get; set; }
    public bool IsMaster { get; set; }
    public int Tag { get; set; }
    public decimal ListPrice { get; set; }
    public decimal PxNakedPrice { get; set; }
    public decimal PxTaxPrice { get; set; }
    public string ImageUrl { get; set; }
    public int ThumbnailCount { get; set; }
    public string ThumbnailUrl1 { get; set; }
    public string ThumbnailUrl2 { get; set; }
    public string ThumbnailUrl3 { get; set; }
    public string ThumbnailUrl4 { get; set; }
    public string ThumbnailUrl5 { get; set; }
    public string ThumbnailUrl6 { get; set; }
    public string ThumbnailUrl7 { get; set; }
    public string ThumbnailUrl8 { get; set; }
    public string ThumbnailUrl9 { get; set; }
    public string ThumbnailUrl10 { get; set; }
    public string ThumbnailUrl11 { get; set; }
    public string ThumbnailUrl12 { get; set; }
    public string ThumbnailUrl13 { get; set; }
    public string Description { get; set; }
    public int MaxQuantity { get; set; }
    public int MinQuantity { get; set; }
    public string Tags { get; set; }
    public string SeoUrl { get; set; }
    public string SeoImageAlt { get; set; }
    public string SeoImageTitle { get; set; }
    public int SalesType { get; set; }
    public string OmsGroup { get; set; }
    public int Packag1 { get; set; }
    public int Packag2 { get; set; }
    public int Packag3 { get; set; }
    public int Packag0 { get; set; }
    public string ProductModel { get; set; }
    public string ExAttribute { get; set; }
    public string JDSKU { get; set; }
    public string JDUrl { get; set; }
    public decimal JDPrice { get; set; }
    public int JDType { get; set; }
    public string JDCategoryId { get; set; }
    public string JDCategoryPath { get; set; }
    public string JDPARAM { get; set; }
    public string PackingList { get; set; }
    public string ProductParameter { get; set; }
    public bool IsSingleBuy { get; set; }
    public int ProductDataSource { get; set; }
    public bool IsDefault { get; set; }
    public string ExtProAttr1 { get; set; }
    public string ExtProAttr2 { get; set; }
    public string ExtProAttr3 { get; set; }
    public string ExtProAttr4 { get; set; }
    public string ExtProAttr5 { get; set; }
    public string ExtProAttr6 { get; set; }
    public string ExtProAttr7 { get; set; }
    public string ExtProAttr8 { get; set; }
    public string ExtProAttr9 { get; set; }
    public string ExtProAttr10 { get; set; }
    public int SaleStatus { get; set; }
    public int Status { get; set; }
    public string Remark { get; set; }
    public string CreatedUser { get; set; }
    public string ModifiedUser { get; set; }
    public long ProductId { get; set; }
    public int isControl { get; set; }
    public string short_name { get; set; }
}