namespace Comix.Cos.Models.EventModels.CosMallProduct;

public class CosSkuDto
{
   public string SkuCode { get; set; }
    public string SkuName { get; set; }
    public int Weight { get; set; }
    public int Stock { get; set; }
    public int AlertStock { get; set; }
    public bool Upselling { get; set; }
    public decimal PxSalePrice { get; set; }
    public decimal PxCostPrice { get; set; }
    public decimal PxTaxPrice { get; set; }
    public decimal PxNakedPrice { get; set; }
    public decimal PxTaxRate { get; set; }
    public string Attribute1 { get; set; }
    public string Attribute2 { get; set; }
    public string Attribute3 { get; set; }
    public int SAU { get; set; }
    public string SkuPackagePes { get; set; }
    public string SkuPackagePac { get; set; }
    public string SkuPackageBox { get; set; }
    public string SkuPackageCar { get; set; }
    public string MaterialNumber { get; set; }
    public string JDSKU { get; set; }
    public string JDUrl { get; set; }
    public decimal JDPrice { get; set; }
    public string ProductSpec { get; set; }
    public string ColorRGB { get; set; }
    public string ProductCode { get; set; }
    public string ColorID { get; set; }
    public string ColorValue { get; set; }
    public string SizeID { get; set; }
    public string SizeValue { get; set; }
    public string SuitableType { get; set; }
    public string SKUImageUrl { get; set; }
    public string B2BSKU { get; set; }
    public decimal SkuRetailPrice { get; set; }
    public decimal SkuSaleUnitPrice { get; set; }
    public string EAN { get; set; }
    public string SkuSaleUnitName { get; set; }
    public string SkuSaleAttribute { get; set; }
    public string SkuAttribute1 { get; set; }
    public string SkuAttribute2 { get; set; }
    public string SourceSKU { get; set; }
    public string CustomerCode { get; set; }
    public string CustomerId { get; set; }
    public string ExtSkuAttr1 { get; set; }
    public string ExtSkuAttr2 { get; set; }
    public string ExtSkuAttr3 { get; set; }
    public string ExtSkuAttr4 { get; set; }
    public string ExtSkuAttr5 { get; set; }
    public string ExtSkuAttr6 { get; set; }
    public string ExtSkuAttr7 { get; set; }
    public string ExtSkuAttr8 { get; set; }
    public string ExtSkuAttr9 { get; set; }
    public string ExtSkuAttr10 { get; set; }
    public int Status { get; set; }
    public bool IsDefault { get; set; }
    public string Remark { get; set; }
    public string CreatedBy { get; set; }
    public string ModifiedBy { get; set; }
    public string JDType { get; set; }
    public string SapSkuCode { get; set; }
    public string TaxCategoryCode { get; set; }
    public long SkuId { get; set; }
}